data_path: data/coco.yaml
conf_file: configs/exp/yolov6n_yaml.py
img_size: 640
batch_size: 28
epochs: 300
workers: 8
device: '1'
eval_interval: 5
eval_final_only: false
heavy_eval_range: 50
check_images: false
check_labels: false
output_dir: result
name: exp
dist_url: env://
gpu_count: 0
local_rank: -1
resume: exp.pt
write_trainbatch_tb: false
stop_aug_last_n_epoch: 10
save_ckpt_on_last_n_epoch: -1
distill: false
distill_feat: false
quant: false
calib: false
teacher_model_path: null
temperature: 20
yaml: null
wandb: false
weights: false
not_infer_on_rect: false
do_pr_metric: false
simota: false
rank: -1
world_size: 1
save_dir: .
